_target_: src.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.05
  weight_decay: 0.00005

net:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: true
  num_classes: 10
